---
- name: weather service deployment
  hosts: weather
  become: yes

  tasks:
    - name: Make sure docker is installed
      apt:
        name: docker.io
        state: present
        update_cache: yes

    - name: Start docker service
      service:
        name: docker
        state: started

    - name: Start weather container
      shell: "docker run -p 5000:5000 -d --restart always segevb/weather_app:{{ tag }}"
